# Generated by Django 6.0.6 on 2026-06-26 11:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loveapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('cover_image', models.ImageField(upload_to='books/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateTimeField()),
                ('category', models.CharField(choices=[('food', 'Food'), ('shopping', 'Shopping'), ('travel', 'Travel'), ('other', 'Other')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='LoveLetter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Outfit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='outfits/')),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='photos/')),
                ('description', models.TextField(blank=True)),
                ('clicked_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='TarotCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='tarot_cards/')),
                ('meaning_upright', models.TextField()),
                ('meaning_reversed', models.TextField()),
                ('suit', models.CharField(blank=True, max_length=50)),
                ('arcana', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('due_date', models.DateTimeField()),
                ('completed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_file', models.FileField(upload_to='videos/')),
                ('description', models.TextField(blank=True)),
                ('recorded_at', models.DateTimeField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='memory',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='memory',
            name='image',
        ),
        migrations.AlterField(
            model_name='memory',
            name='created_at',
            field=models.DateTimeField(),
        ),
        migrations.AddField(
            model_name='memory',
            name='photos',
            field=models.ManyToManyField(blank=True, related_name='memories', to='loveapi.photo'),
        ),
        migrations.CreateModel(
            name='TarotReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('interpretation', models.TextField(blank=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='loveapi.tarotcard')),
            ],
        ),
        migrations.AddField(
            model_name='memory',
            name='videos',
            field=models.ManyToManyField(blank=True, related_name='memories', to='loveapi.video'),
        ),
    ]
