# Generated by Django 6.0.6 on 2026-06-26 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loveapi', '0003_daymanager_expense_priority'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarotreading',
            name='card',
        ),
        migrations.AddField(
            model_name='tarotreading',
            name='cards',
            field=models.ManyToManyField(related_name='readings', to='loveapi.tarotcard'),
        ),
    ]
