# Generated by Django 6.0.6 on 2026-06-26 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loveapi', '0004_remove_tarotreading_card_tarotreading_cards'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='rating',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
