# Generated by Django 6.0.6 on 2026-06-29 19:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loveapi', '0006_playlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memory',
            name='photos',
        ),
        migrations.RemoveField(
            model_name='memory',
            name='videos',
        ),
        migrations.AddField(
            model_name='photo',
            name='memory',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='loveapi.memory'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='video',
            name='memory',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='loveapi.memory'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='memory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
