# Generated by Django 6.0.6 on 2026-06-29 23:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loveapi', '0007_remove_memory_photos_remove_memory_videos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='day',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='loveapi.daymanager'),
            preserve_default=False,
        ),
    ]
