# Generated by Django 6.0.6 on 2026-06-29 23:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loveapi', '0008_task_day'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='day',
        ),
    ]
