# Generated by Django 6.0.6 on 2026-07-01 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loveapi', '0009_remove_task_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='loveletter',
            name='title',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
