# Generated by Django 6.0.6 on 2026-07-01 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loveapi', '0011_expense_note_alter_expense_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='priority',
        ),
    ]
