# Generated by Django 6.0.6 on 2026-07-01 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loveapi', '0012_remove_expense_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(max_length=20),
        ),
    ]
