# Generated by Django 6.0.6 on 2026-07-01 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loveapi', '0013_alter_expense_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='clicked_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='recorded_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
