# Generated by Django 6.0.6 on 2026-07-01 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loveapi', '0014_alter_photo_clicked_at_alter_video_recorded_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarotcard',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='tarot_cards/'),
        ),
    ]
