# Generated by Django 6.0.6 on 2026-07-01 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loveapi', '0015_alter_tarotcard_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarotcard',
            name='image',
        ),
    ]
